static const char black[] = "#0a0e14"; // Background color
static const char luckydog[] = "#d3c8ba";
static const char grayishblue[] = "#2a2f3a";
static const char gray2[] = "#181b23"; // Unfocused window border
static const char gray3[] = "#1f1d2e"; // Slightly darker muted tones
static const char gray4[] = "#26233a"; // Mid-level highlight
static const char blue[] = "#4d8dc4";  // Focused window border
static const char arapawa_blue[] = "#264662";
static const char green[] = "#a1c05d";         // Green accents
static const char red[] = "#d36c6c";           // Red highlights
static const char orange[] = "#e7a953";        // Golden tones
static const char yellow[] = "#f6c982";        // Bright yellow
static const char pink[] = "#b18bbb";          // Magenta-like pink
static const char col_borderbar[] = "#0a0e14"; // Inner border
